#### Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов:

#### Футболисты: 173, 175, 180, 178, 177, 185, 183, 182. 
#### Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180. 
#### Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [1]:
import numpy as np 
from scipy.stats import f_oneway

In [2]:
football = np.array([173, 175, 180, 178, 177, 185, 183, 182])
hockey = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
weightlifter = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [9]:
football_mean = round(football.mean(), 2)
football_mean

179.12

In [8]:
hockey_mean = round(hockey.mean(), 2)
hockey_mean

178.67

In [10]:
weightlifter_mean = round(weightlifter.mean(), 2)
weightlifter_mean

172.73

$${y_i} = \displaystyle \frac{1}{n_i} \sum_{j=1}^{n_i} y_{ij}$$
$${football} = 179.12$$
$${hockey} = 178.66$$
$${weightlifter} = 172.72$$

In [12]:
Y = np.hstack((football, hockey, weightlifter))
Y_mean = round(Y.mean(), 2)
Y_mean

176.46

$$\overline{Y} = \displaystyle \frac{1}{n} \sum_{i=1}^{k} \sum_{j=1}^{n_i} y_{ij} = 176.464$$

In [13]:
S2_F = (football_mean - Y_mean)**2 * len(football) + (hockey_mean - Y_mean)**2  * len(hockey) + (weightlifter_mean - Y_mean)**2 * len(weightlifter)
S2_F

253.6036000000005

$$S_F^2 = \displaystyle \sum_{i=1}^{k} (y_{i} - \overline{Y})^2 =253.907$$

In [14]:
S2_res = ((football - football_mean)**2).sum() + ((hockey - hockey_mean)**2).sum() + ((weightlifter - weightlifter_mean)**2).sum()
S2_res

577.0572

$$S^2_{\text{ост}} = \sum_{i=1}^{k} \sum_{j=1}^{n_i} (y_{ij} - \overline{y_i})^2 = 577.057$$

In [15]:
q2_F = S2_F / (3 - 1)
q2_F

126.80180000000026

$$\sigma^2_F = \frac{S_F^2}{k - 1} = 126.954$$

In [16]:
q2_res = S2_res / (len(Y) - 3)
q2_res

23.082288

$$\sigma^2_{\text{ост}} = \frac{S^2_{\text{ост}}}{n - k} = 23.082$$

In [18]:
F_н = q2_F / q2_res
F_н

5.49346754533174

$$F_H = \frac{\sigma^2_F}{\sigma^2_{\text{ост}}} = 5.500$$
$$F_{\text{крит.}} = 3.38 \quad \text{при }\alpha = 0.05$$
$$5.500 &gt; 3.38$$
Различия между группами статистически значимы на уровне значимости 0.05.

In [19]:
f_oneway(football, hockey, weightlifter)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)